#!/bin/bash
  set terminal png
  set output 'image.png'
  plot 'lcs.data' with linespoints
  set logscale x 10
  set xlabel "Time (Seconds)"
  set ylabel "Size (N)"
  plot 'lcs.data' using 1:3 with linespoints
  set title "My LCS algorithm"
  f(x) = A*x**2
  fit f(x) 'lcs.data' via A
  plot 'lcs.data' using 1:3 with linespoints, f(x)
  replot
  reread
  pause -1 "Enter any to continue"
